---
driver:
  name: docker
  socket: tcp://weirdscience:2375
  # name: vagrant
  # require_chef_omnibus: 12.19.36


provisioner:
  name: docker
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  # name: winrm
  # elevated: true
  
platforms:
  # - name: windows-2012r2
  #   driver:
  #     customize:
  #       memory: 4096

suites:
  - name: default
    run_list:
      - recipe[poolse::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
    driver:
      network:
        # - ["private_network", { ip: "172.28.128.11" }]        
